In [192]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [193]:
dataframe = sns.load_dataset('iris')

In [194]:
print(dataframe.shape)
dataframe.head()

(150, 5)


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [195]:
import random
def loadDataset(split, trainingSet=[], testSet=[]):
    dataset = list(dataframe.to_numpy())
    for x in range(len(dataset)-1):
        for y in range(4):
            dataset[x][y] = float(dataset[x][y])
        if random.random() < split:
            trainingSet.append(dataset[x])
        else:
            testSet.append(dataset[x])

In [196]:
trainingSet=[]
testSet=[]
loadDataset(0.66,trainingSet,testSet)
print('Train: '+ repr(len(trainingSet)))
print('Test: '+repr(len(testSet)))
testSet

Train: 102
Test: 47


[array([5.1, 3.5, 1.4, 0.2, 'setosa'], dtype=object),
 array([4.6, 3.4, 1.4, 0.3, 'setosa'], dtype=object),
 array([4.8, 3.4, 1.6, 0.2, 'setosa'], dtype=object),
 array([4.8, 3.0, 1.4, 0.1, 'setosa'], dtype=object),
 array([5.8, 4.0, 1.2, 0.2, 'setosa'], dtype=object),
 array([5.7, 3.8, 1.7, 0.3, 'setosa'], dtype=object),
 array([5.1, 3.8, 1.5, 0.3, 'setosa'], dtype=object),
 array([5.4, 3.4, 1.7, 0.2, 'setosa'], dtype=object),
 array([4.6, 3.6, 1.0, 0.2, 'setosa'], dtype=object),
 array([5.0, 3.4, 1.6, 0.4, 'setosa'], dtype=object),
 array([4.4, 3.0, 1.3, 0.2, 'setosa'], dtype=object),
 array([4.8, 3.0, 1.4, 0.3, 'setosa'], dtype=object),
 array([7.0, 3.2, 4.7, 1.4, 'versicolor'], dtype=object),
 array([6.4, 3.2, 4.5, 1.5, 'versicolor'], dtype=object),
 array([5.5, 2.3, 4.0, 1.3, 'versicolor'], dtype=object),
 array([4.9, 2.4, 3.3, 1.0, 'versicolor'], dtype=object),
 array([5.2, 2.7, 3.9, 1.4, 'versicolor'], dtype=object),
 array([6.1, 2.9, 4.7, 1.4, 'versicolor'], dtype=object),
 arr

In [197]:
import math
def euclideanDistance(instance1, instance2, length):
    distance = 0
    for x in range(length):
        distance += pow((instance1[x] - instance2[x]),2)
    return math.sqrt(distance)

In [198]:
#testing euclideanDistance function
data1 = [2,2,2,'a']
data2 = [4,4,4,'b']
euclideanDistance(data1,data2,3)

3.4641016151377544

In [199]:
import operator
def getNeighbors(trainingSet, testInstance, k):
    distances = []
    length = len(testInstance)-1
    for x in range(len(trainingSet)):
        dist = euclideanDistance(testInstance, trainingSet[x], length)
        distances.append((trainingSet[x], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors=[]
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors

In [200]:
#testing getNeighbor function
trainSet = [[2,2,2,'a'],[4,4,4,'b']]
testInstance = [5,5,5]
k=1
getNeighbors(trainSet, testInstance,k)

[[4, 4, 4, 'b']]

In [201]:
import operator
def getResponse(neighbors):
    classVotes = {}
    for x in range(len(neighbors)):
        response = neighbors[x][-1]
        if response in classVotes:
            classVotes[response] += 1
        else:
            classVotes[response] = 1
    sortedVotes = sorted(classVotes.items(), key=operator.itemgetter(1),reverse=True)
    return sortedVotes[0][0]

In [202]:
#testing getResponse function
neighbors=[[1,1,1,'a'],[2,2,2,'a'],[3,3,3,'b']]
getResponse(neighbors)

'a'

In [203]:
def getAccuracy(testSet, predictions):
    correct = 0
    for x in range(len(predictions)):
        if testSet[x][-1] is predictions[x]:
            correct += 1
    return (correct/float(len(predictions)))*100

In [204]:
#testing getAccuracy function
testSet = [[1,1,1,'a'], [2,2,2,'a'],[3,3,3,'b']]
predictions = ['a','a','a']
accuracy = getAccuracy(testSet,predictions)
print(accuracy)

66.66666666666666


In [205]:
def knn():
    trainingSet=[]
    testSet=[]
    split=0.6
    loadDataset(split,trainingSet, testSet)
    print('Train set:' + repr(len(trainingSet)))
    print('Test set:' + repr(len(testSet)))
    k=3
    predictions=[]
    for i in range(len(y_train)):
        neighbors = getNeighbors(trainingSet,testSet[i],k)
        result = getResponse(neighbors)
        predictions.append(result)
        print('Predicted = '+ repr(result) + ', actual = ' +repr(testSet[i][-1]))
    accuracy = getAccuracy(testSet, predictions)
    print('Accuracy = ' + repr(accuracy) + '%')

knn()

Train set:89
Test set:60
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'setosa', actual = 'setosa'
Predicted = 'versicolor', actual = 'versicolor'
Predicted = 'versicolor', actual = 'versicolor'
Predicted = 'versicolor', actual = 'versicolor'
Predicted = 'virginica', actual = 'versicolor'
Predicted = 'versicolor', actual = 'versicolor'
Predicted = 'versicolor', actual = 'versicolor'
Predicte