In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [3]:
dataset = datasets.load_iris()

In [4]:
model = GaussianNB()
model.fit(dataset.data, dataset.target)

GaussianNB()

In [5]:
model

GaussianNB()

In [6]:
expected = dataset.target
predicted = model.predict(dataset.data)

In [7]:
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
